[bugfix,model/dataset][xs]: move location of setting of ckan_uri to avoid error.
* Error of form (broke pretty much all tests) of form: "AttributeError: 'Dataset' object has no attribute 'dataset'." (on use of self.dataset in self._load).  (NB: tests still not passing for me due to other errors (same errors on master ...)).